#ifndef QEPIGDATAFOURIERANALYSISLIB_GLOBAL_H
#define QEPIGDATAFOURIERANALYSISLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QEPIGDATAFOURIERANALYSISLIB_LIBRARY)
#  define QEPIGDATAFOURIERANALYSISLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QEPIGDATAFOURIERANALYSISLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QEPIGDATAFOURIERANALYSISLIB_GLOBAL_H
